[gcp_service_account]
type = "service_account"
project_id = "data-maturity-survey"
private_key_id = "1be6935632420520b98fc144adf32ae254f6e2d5"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC+E5ivsptCl1FP
L1kQXb1sM+6ElsPg0i1g3FEhfLmR90aNCi0F/WvHuCZl4fOdkiSMYkSxmL3J7d4v
CmIBX2wZPUO0V/cOF0t+QRh8RR6FFW5cNWGGyN9JeN49G8cJKF9SMXN3BfEy8ywB
uqe1TjOqlvoqk35mQEg/9gbFy6hNNYYoeQxthiavwVrawezgynGTxLDWpxVSlWhH
c9iRV9YxXqTKi/DvraUQRN5Io8wUi2GS0rWMPsiRljD8mGUDh1kb2EfEr7D/jtIm
0rzwJy7QQeRnwQo9GsAryB0pgNp+fIA2X5Ny0CDC+LOe715+XJ+sonRc1umzpB+z
q5+5luQZAgMBAAECggEAMD9yLPsVzRfy5Do9Ddn1mK8v9sj8TKedLC6Qi4MI6cPO
TUPNfO1AfBBC8u6hc5hinZ3eGQSP/F9cXC1zBi0uF9QEyRThGdsQ5ynn6Ld00UxI
2LAWIuv/PbuoEfPomGr+kzMJP6eq+4ddXsz+ABgrJjyvoLoSxirADDhLrM6O2JXz
B1kd0SXxoe/yZkwpPso4VGKYuqKAT01pNq0BZpI6UBtQgH6UgB9o0GZrjmzpBnWm
ijAZLfEEOPzQK79BpzkPUkrmvBXhSriwXdojdrgsKLMZIJyIOCXgj4paE/a4jdyR
XPaB6ldaAsrwm1ZwEnjX5iFzT7AhHhkazvz+Jz+xlwKBgQDg3QVvAjoIiIGwX0XZ
p4z/kwtKlLjDr6wS7OSo1H4oBKECrIQ/Pi2JyfjlVkU87aQqTIS7oOrBjoHZynOM
Z/7oWOGgfaVQ2YVf3gwPED1lUtWZceDn+4dr0/V15FDCWqNDUBalB83xXXRmFS0H
T4C0Xb2Kfd+2oXxT9G6VoU1SRwKBgQDYZXLfq+NBHFoq/YLeWzAtqN7uUFi/n3vr
QSYqIo96O4UMDIQwfG8AvVVCn3Z9T4jYINifnA7AldGO/qGQ5Ws9VaVYrfV6wRRB
dH7a27XCba8dEWFo6yx5sWETIBav6RuVSNYr4Br2nhBJ1y3sxWK8Cr1Xmy/JejIP
x4VJnbPmnwKBgQC3MjpoC0dehmAqYiRVRBUybwkG9Q1mmCu3q3pLNful/Md0lzqT
D8Qn+v2lUljMX8ucjoShHGPF16Vg23iyDlP11dvUVikmKmFoDk6CwzdR4l+VSNr0
BM96gM/9AUruXMugXpJkV2xoVTwsotnxl8sCp1BxkUV+1Cenen/Rtf15pwKBgHr3
Qwy5Bz1DmDVfs5MZLEp18KBphdT2Epu/fKlq1C84TUVog2FuBEHeVOmz5cgVfwSZ
vZ8NNhDX0ao5JaRJyeOjnH7E836a4yDCyycgvKtMWrrg2oKdSLuqQSh2Do5Nn3/4
UMPD6G6FqWncXdty2sVSMP/sTn5l8ramwSXw+H6vAoGAeK2oV3X3KZUnhvF4LwlN
FwUG5m+2pnMD/JwSNQwlcniQDc7ALloj52ewJ/h9ct/BxZRd18X2o72NKoQ/4G8F
M9gaUoDcNYhVkMK5zib0oVHsyAnSl7SqXIBR/oyF5Ea89dCA6IKUL73l0vFOEiyW
Dg0RkxxmY9Xs7hVPimrGJFE=
-----END PRIVATE KEY-----"""
client_email = "datamat@data-maturity-survey.iam.gserviceaccount.com"
client_id = "115139794868796576561"